# Generated by Django 3.2.6 on 2021-08-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is the softest shirt you will ever wear. Slim fitting and slightly cropped shirt made in our lightweight, crazy-soft Cloudkrit fabric.'),
            preserve_default=False,
        ),
    ]
