# Generated by Django 3.2.6 on 2021-08-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
