# Generated by Django 3.2.6 on 2021-08-07 23:31

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_order_billing_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingadress',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
