# Generated by Django 3.2.6 on 2021-08-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0019_auto_20210812_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
