# Generated by Django 3.2.6 on 2021-08-12 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0020_order_ref_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='refund',
            new_name='refund_granted',
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.order')),
            ],
        ),
    ]
