# Generated by Django 3.2.6 on 2021-08-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0025_auto_20210817_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
        migrations.AddField(
            model_name='item',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
